version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
    - db_data:/var/lib/postgresql/data
  raven:
    image: hasura/graphql-engine:v1.0.0-alpha28
    depends_on:
    - "postgres"
    restart: always
    environment:
    - POSTGRES_PASSWORD=mysecretpassword
    - HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:mysecretpassword@postgres:5432/postgres
    - HASURA_GRAPHQL_ENABLE_CONSOLE=false
    - HASURA_GRAPHQL_ACCESS_KEY
    - HASURA_GRAPHQL_UNAUTHORIZED_ROLE=anonymous
  server:
    image: cmdb-server
    environment:
    - HASURA_URL=http://raven:8080/v1alpha1/graphql
    - HASURA_GRAPHQL_ACCESS_KEY
    - PRODUCTION=true
    - APP_ROOT=/cmdb
    build:
      context: server
      dockerfile: Dockerfile
    restart: always
    depends_on:
    - "raven"
  caddy:
    image: abiosoft/caddy:0.11.0
    depends_on:
    - "server"
    restart: always
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./Caddyfile:/etc/Caddyfile
    - caddy_certs:/root/.caddy
volumes:
  db_data:
  caddy_certs:
