version: '3.6'
services:
  server:
    image: nebelungcat/cmdb-server:v1.1
    ports:
    - "9000:9000"
    restart: always
    volumes:
    - ../server/src:/app/src
  postgres:
    image: postgres
    environment:
    - "POSTGRES_PASSWORD:mysecretpassword"
    ports:
    - "6432:5432"
    volumes:
    - db_data:/var/lib/postgresql/data
  raven:
    image: hasura/graphql-engine:4d2d2ca
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
    - "POSTGRES_PASSWORD:mysecretpassword"
    command: >
      /bin/sh -c "
      raven --database-url postgres://postgres:$${POSTGRES_PASSWORD}@postgres:5432/postgres serve;
      "
volumes:
  db_data:
