version: '3.6'
services:
  server:
    image: nebelungcat/cmdb-server:v1.1
    environment:
      HASURA_GRAPHQL_ACCESS_KEY: abcd
    ports:
    - "9000:9000"
    restart: always
    volumes:
    - ../server/src:/app/src
  postgres:
    image: postgres
    restart: always
    environment:
    - "POSTGRES_PASSWORD:mysecretpassword"
    ports:
    - "6432:5432"
    volumes:
    - db_data:/var/lib/postgresql/data
  raven:
    image: hasura/graphql-engine:v1.0.0-alpha28
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:mysecretpassword@postgres:5432/postgres
      HASURA_GRAPHQL_ACCESS_KEY: abcd
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
volumes:
  db_data:
