version: '3.6'
services:
  server:
    image: nebelungcat/cmdb-server:v1.1
    environment:
    - HASURA_URL
    ports:
    - "9000:9000"
    restart: always
    volumes:
    - ../server/src:/app/src
  postgres:
    image: postgres
    restart: always
    environment:
    - "POSTGRES_PASSWORD:mysecretpassword"
    ports:
    - "6432:5432"
    volumes:
    - db_data:/var/lib/postgresql/data
  raven:
    image: hasura/graphql-engine:v1.0.0-alpha20
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
    - "POSTGRES_PASSWORD:mysecretpassword"
    command: >
      /bin/sh -c "
      graphql-engine --database-url postgres://postgres:$${POSTGRES_PASSWORD}@postgres:5432/postgres serve;
      "
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 7000:8080
volumes:
  db_data:
